//use aoc::day1;
//use aoc::day2;
//use aoc::day3;
//use aoc::day4;
//use aoc::day5;
//use aoc::day6;
//use aoc::day7;
//use aoc::day8;
//use aoc::day9;
//use aoc::day10;
//use aoc::day11;
//use aoc::day12;
use aoc::day13;

fn main() {
    //day1::part1_naive();
    //day1::part1();
    //day1::part2_naive();
    //day1::part2();
    //day2::part1();
    //day2::part2();
    //day3::part1();
    //day3::part2();
    //day4::part1();
    //day4::part2();
    //day5::part1();
    //day5::part2();
    //day6::part1();
    //day6::part2();
    //day7::part1();
    //day7::part2();
    //day8::part1();
    //day8::part2();
    //day9::part1();
    //day9::part2();
    //day10::part1();
    //day10::part2();
    //day11::part1();
    //day11::part2();
    //day12::part1();
    //day12::part2();
    day13::part1();
    day13::part2();
}
